### ISSUE TITLE
Exit code does not equal number of failed jobs anymore

### ISSUE THREAD

**Issue by vinjana** [TheRoddyWMS/Roddy#167]
Recent changes in BatchEuphoria made the implementation of the exit code equaling the number of failed jobs hard.

In `de.dkfz.roddy.Roddy#performCLIExit(de.dkfz.roddy.client.RoddyStartupModes, int)` implement

* collect all actually executed ExecutionContexts (i.e. for all datasets)
* get all jobs from the IDs
* for each job get the job state with queryJobStates
  * first, get them from the job manager
  * for those already lost from the terminated job cache, get the exit code from the jobStateLogfile.txt

**Comment by vinjana** [comment]
Relevance: Feature was used by PanCancer.

**Comment by dankwart-de** [comment]
Don't think this feature is used somewhere else. Also it is easy to just check the jobstate log. Return 0 or 1 might be easiest. Also think, that large workflows with > 255 jobs never return the proper number. I would close it for now.

**Comment by dankwart-de** [comment]
I changed it so, that waitForJobs works again. However, it will not return the number of failed jobs and will return 1.
See #318

**Comment by vinjana** [comment]
Agree.

**Comment by vinjana** [comment]
Won't be done with counts. See #318.
