### ISSUE TITLE
If compileplugin is used and there is no Roddy.jar in dist/bin/develop, compilation will not work and will not show an error.

### ISSUE THREAD

**Issue by dankwart-de** [TheRoddyWMS/Roddy#206]

**Comment by vinjana** [comment]
Solution: Execute compile roddy (gradlew build) before?

**Comment by dankwart-de** [comment]
I need to put in a check if the Roddy.jar ist available. Just compiling Roddy will not always work AND you might not have write access. So better check and fail and let the user react.

**Comment by dankwart-de** [comment]
See #216
