### ISSUE TITLE
Investigate: Would the jgitflow-gradle-plugin be suited for us?

### ISSUE THREAD

**Issue by vinjana** [TheRoddyWMS/Roddy#208]
https://github.com/RobWin/jgitflow-gradle-plugin supports GitFlow release procedure with (limited?) semantic versioning support.

* How is the "look & feel" of the plugin? Is it convenient?
* Are versions correctly updated?
* Would it fit with our release startegy?
* Can we fit it with our current versioning mechanism with buildversion.txt? Should be remove the buildversion.txt?

**Comment by dankwart-de** [comment]
You already tried this right? Or was it something similar?

**Comment by vinjana** [comment]
The current simplified flow -- without develop branch -- is fine as it is. I think in the moment, we do not need this plugin. This issue can be closed for now, and reopened if necessary.
