### ISSUE TITLE
COMPLETED_SUCCESSFUL is set in BE.ExecutionService when qsub exited with 0

### ISSUE THREAD

**Issue by vinjana** [TheRoddyWMS/Roddy#222]
COMPLETED_SUCCESSFUL is set by BE.ExecutionService, when the execution result is successful, i.e. the qsub, not when the job finished successfully on the cluster!

1. Clarify the semantics of COMPLETED_SUCCESSFUL. When job succeeded, or when execution succeeded?
2. Write the correct status line in Roddy.Job.appendToJobStateLogfile()

**Comment by dankwart-de** [comment]
1. COMPLETED_SUCCESSFUL is meant to be the state of a successfully finished job. Not a submitted one.
   The proper status should therefore be SUBMITTED_UNKNOWN or just SUBMITTED

**Comment by vinjana** [comment]
Moved to https://github.com/TheRoddyWMS/BatchEuphoria/issues/117
