### ISSUE TITLE
Check if $RODDY_SCRATCH writable before starting to submit jobs

### ISSUE THREAD

**Issue by GWarsow** [TheRoddyWMS/Roddy#239]

**Comment by vinjana** [comment]
This is not possible in all cases. RODDY_SCRATCH is often derived from the local scratch directories on the cluster, that are only created as soon as the job is started, but not earlier.

One could add a test to the wrapper script that ensures RODDY_SCRATCH is readable/writable/executable (dir), before the actual analysis script is started. Would that be o.k.?

**Comment by dankwart-de** [comment]
I'll implement it this way.

**Comment by dankwart-de** [comment]
See https://github.com/TheRoddyWMS/Roddy-Default-Plugin/pull/10
