### ISSUE TITLE
Restore functional ForbidSubmissionOnRunning feature

### ISSUE THREAD

**Issue by vinjana** [TheRoddyWMS/Roddy#300]
We just had two cases, where our automation server died due to VM error and when restarted did not recognize that a specific workflow instance was already running. It then instead resubmitted the same workflow resulting in corrupt data (though recognizable, because the files were not parsible).

Generally, recognizing whether a workflow/job is already running is a good thing that can save many hours of computation time (think of jobs running for a very long time). I think this safety-feature should not be turned off by default, as it used to be with the old feature-toggle, but should be turned on by default. 

Currently, the feature is broken and needs to be fixed.

**Comment by dankwart-de** [comment]
See #317 , seems to work. Don't know, why we disabled it.

**Comment by vinjana** [comment]
Fine. Then this can get closed.
