### ISSUE TITLE
Workflow.getSourceFiles cannot find files behind symlinks

### ISSUE THREAD

**Issue by npeschke** [TheRoddyWMS/Roddy#306]
The method `de.dkfz.roddy.core.Workflow.getSourceFiles(File path, Regex regex, FileSystemAccessProvider.RegexSearchDepth depth, String _class = BaseFile.STANDARD_FILE_CLASS)` 
is not able to find retrieve source files from the file system if they are behind symlinks.
this might be solved by adding a new filetype to 
`de.dkfz.roddy.execution.io.fs.BashCommandSet.getListFullDirectoryContentRecursivelyCommand(File f, int depth, FileType selectedType, boolean detailed)`
such that the find command will look like this:
`find "<DIRECTORY>" -type f -or -type l`
compared to the current
`find "<DIRECTORY>" -type f`
which only lists regular files.

**Comment by npeschke** [comment]
Alternatively it would be possible to change
```
ExecutionResult result = ExecutionService.instance.execute(commandSet.getListFullDirectoryContentRecursivelyCommand(baseFolder, -1, FileType.FILES, false))

to

ExecutionResult result = ExecutionService.instance.execute(commandSet.getListFullDirectoryContentRecursivelyCommand(baseFolder, -1, FileType.ANY, false))
```

in `de.dkfz.roddy.execution.io.fs.FileSystemAccessProvider.listFilesUsingRegex(File baseFolder, String regex, RegexSearchDepth scope)`

**Comment by dankwart-de** [comment]
See #315
